- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: CONNECTIONSTRINGS__NOSUCHDB
      valueFrom: 
        secretKeyRef:
          name: some-db-secret
          key: connection
