apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../base

patches:
  - target:
      kind: Ingress
      name: hello-world-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: hello-world.fancy.net
  - target:
      kind: Deployment
      name: hello-world-deployment
    path: deployment-patch.yml

# patchesStrategicMerge:
#   - deployment.yml
