name: build-and-test

on:
  push:
    branches-ignore: 
      - 'main'
  pull_request:
    branches-ignore: 
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Run kustomize
      run: |
        ls
        kustomize edit set image hello-world=ghcr.io/pedrofranco-vestas/hello-world:1.2.3
        kustomize build ./.k8s/dev -o hello-world.deployment.yaml
        
    - name: View manifest
      run: |
        ls
        cat hello-world.deployment.yaml

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with: 
        useConfigFile: true
    
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ steps.gitversion.outputs.SemVer }}
    
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Build artifacts
      run: dotnet publish ./HelloWorld -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish/api/ -r win-x64 -p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Create nuget package from publish
      uses: cake-build/cake-action@v1
      with:
        script-path: nuget.cake
        target: Create-Nuget
        verbosity: Diagnostic
        arguments: |
          srcPath: "publish/api/*.*"
          nuspecPath: "./HelloWorld/HelloWorld.nuspec"
          libraryVersion: "${{ steps.gitversion.outputs.SemVer }}"
          nugetOutput: "publish/nupkg"

    - name: Pack artifacts
      uses: papeloto/action-zip@v1
      with:
        dest: hello-world-win-x64-v${{ steps.gitversion.outputs.SemVer }}.zip
        files: publish/
    
    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-v${{ steps.gitversion.outputs.SemVer }}
        path: ./*.zip