name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with: 
        useConfigFile: true
    
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ steps.gitversion.outputs.SemVer }}
    
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

  fake-deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
