name: notify-teams

on:
  deployment_status:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Notify people
      if: ${{github.event.deployment_status.state == 'success'}}
      run: |
        curl -H 'Accept: */*' -H 'Content-Type: application/json' \
            --data-raw '{\
            "@context":"http://schema.org/extensions",\
            "@type":"MessageCard",\
            "summary":"New deployment",\
            "title":"Deployment at ${{github.repository}}",\
            "text":"${{github.triggering_actor}} has carried out a new **deployment** at [this repository](${{github.event.deployment_status.deployment_url}})"}' \
            ${{ secrets.URI_HOOK }}
