name: notify-teams

on:
  deployment_status:

jobs:
  notify:
    if: ${{github.event.deployment_status.state == 'success'}}
    runs-on: ubuntu-latest

    steps:
    - name: Notify people
      run: >
        curl -H 'Accept: */*' -H 'Content-Type: application/json' --data-raw \
          '{\
            "@context":"http://schema.org/extensions", \
            "@type":"MessageCard", \
            "summary":"New deployment", \
            "title":"Deployment at ${{github.server_url}}/${{github.repository}} (${{github.event.deployment_status.environment}})", \
            "text":"${{github.triggering_actor}} has carried out a new [deployment](${{github.event.deployment_status.deployment_url}}) on [this repository](${{github.server_url}}/${{github.repository}})"\
          }' \
          ${{ secrets.URI_HOOK }}
