name: release

on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with: 
        useConfigFile: true

    - name: Get tag number
      run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Check value
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.event.action }}
        echo $TAG_VERSION
        echo ${{ env.TAG_VERSION }}
    
    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{ steps.gitversion.outputs.SemVer }}
    
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Build artifacts
      run: dotnet publish ./HelloWorld -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish/ -r win-x64 -p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Create nuget package from publish
      uses: cake-build/cake-action@v1
      with:
        script-path: nuget.cake
        target: Create-Nuget
        verbosity: Diagnostic
        arguments: |
          srcPath: "publish/*.*"
          nuspecPath: "./HelloWorld/HelloWorld.nuspec"
          libraryVersion: "${{ steps.gitversion.outputs.SemVer }}"
          nugetOutput: "."

    - name: Create release with new tag name
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
      with:
        files: ./*.nupkg
        tag_name: ${{ steps.gitversion.outputs.SemVer }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release with incoming tag name
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
      with:
        files: ./*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Package
      run: |
        dotnet nuget add source --username vestas-power-solutions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vestas-power-solutions/index.json"
        dotnet nuget push "./*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
