name: test-env-vars

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Set env variables
      run: |
        $env:MyVar = "some value" >> $GITHUB_ENV
        $env:RefName = ${env:GITHUB_REF_NAME} >> $GITHUB_ENV
        echo "$env:MyVar='some value'" >> $GITHUB_ENV
        echo "$env:RefName=${env:GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "myvar is ${env:MyVar}"
        echo "RefName is ${env:RefName}"

    - name: Show all variables
      run: env

    - name: Show my variables
      run: |
        echo "myvar is ${env:MyVar}"
        echo "RefName is ${env:RefName}"
