name: test-env-vars

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with: 
        useConfigFile: true

    - name: Build artifacts
      run: dotnet publish ./HelloWorld -c Release -r win-x64 --self-contained --nologo --output publish/api/ -p:Version=${{ steps.gitversion.outputs.SemVer }} -p:PublishTrimmed=true

    - name: Create nuget package from publish
      uses: cake-build/cake-action@v1
      with:
        script-path: nuget.cake
        target: Create-Nuget
        verbosity: Normal
        arguments: |
          srcPath: "publish\api\*.*"
          nuspecPath: "./HelloWorld/HelloWorld.nuspec"
          libraryVersion: "${{ steps.gitversion.outputs.SemVer }}"
          nugetOutput: "artifacts/"

    - name: Publish Packages
      run: |
        ls -aAl
        dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"    
    
    # - name: Set env variables
    #   run: |
    #     echo "MyVar='some value 2'" >> $env:GITHUB_ENV
    #     echo "RefName=${env:GITHUB_REF_NAME}" >> $env:GITHUB_ENV
    #     echo "RefNameSecond=${env:GITHUB_REF_NAME#feature/}" >> $env:GITHUB_ENV
    #     echo "RefNameThird=${env:GITHUB_REF_NAME.replace('feature/', '')}" >> $env:GITHUB_ENV
    #     echo "RefNameFourth=$env:GITHUB_REF_NAME.replace('feature/', '')" >> $env:GITHUB_ENV
    #     echo "RefNameFifth=$env:GITHUB_REF_NAME#feature/" >> $env:GITHUB_ENV
    #     echo ("RefNameSixth=" + $env:GITHUB_REF_NAME.replace('feature/', '')) >> $env:GITHUB_ENV
    #     echo "RefNameSeventh={$env:GITHUB_REF_NAME#feature/}" >> $env:GITHUB_ENV
    #     $RefNameEighth = ${env:GITHUB_REF_NAME}.replace('feature/', '')
    #     echo "RefNameEighth=$RefNameEighth" >> $env:GITHUB_ENV

    # - name: Show all variables
    #   run: env

    # - name: Show my variables
    #   run: |
    #     echo "myvar is ${env:MyVar}"
    #     echo "RefName is ${env:RefName}"
    #     echo "RefNameSecond is ${env:RefNameSecond}"
    #     echo "RefNameThird is ${env:RefNameThird}"
    #     echo "RefNameFourth is ${env:RefNameFourth}"
    #     echo "RefNameFifth is ${env:RefNameFifth}"
    #     echo "RefNameSixth is ${env:RefNameSixth}"
    #     echo "RefNameSeventh is ${env:RefNameSeventh}"
    #     echo "RefNameEighth is ${env:RefNameEighth}"
    #     # ${{ env.RefNameEighth }}
