name: test-env-vars

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set env variables
      run: |
        echo "MyVar='some value 2'" >> $env:GITHUB_ENV
        echo "RefName=${env:GITHUB_REF_NAME}" >> $env:GITHUB_ENV
        echo "RefNameSecond=${env:GITHUB_REF_NAME#feature/}" >> $env:GITHUB_ENV
        echo "RefNameThird=${env:GITHUB_REF_NAME.replace('feature/', '')}" >> $env:GITHUB_ENV
        echo "RefNameFourth=$env:GITHUB_REF_NAME.replace('feature/', '')" >> $env:GITHUB_ENV
        echo "RefNameFifth=$env:GITHUB_REF_NAME#feature/" >> $env:GITHUB_ENV
        # echo "RefNameSixth=" + $env:GITHUB_REF_NAME.replace('feature/', '') >> $env:GITHUB_ENV
        echo "RefNameSeventh={$env:GITHUB_REF_NAME#feature/}" >> $env:GITHUB_ENV
        $RefNameEighth = ${env:GITHUB_REF_NAME}.replace('feature/', '')
        echo "RefNameEighth=$RefNameEighth" >> $env:GITHUB_ENV

    - name: Show all variables
      run: env

    - name: Show my variables
      run: |
        echo "myvar is ${env:MyVar}"
        echo "RefName is ${env:RefName}"
        echo "RefNameSecond is ${env:RefNameSecond}"
        echo "RefNameThird is ${env:RefNameThird}"
        echo "RefNameFourth is ${env:RefNameFourth}"
        echo "RefNameFifth is ${env:RefNameFifth}"
        # echo "RefNameSixth is ${env:RefNameSixth}"
        echo "RefNameSeventh is ${env:RefNameSeventh}"
        echo "RefNameEighth is ${env:RefNameEighth}"
        ${{ env.RefNameEighth }}
