name: workflow-without-master

on:
  push:
    branches-ignore: 
      - 'main'
  pull_request:
    branches-ignore: 
      - 'main'
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Adding GitHub packages
      run: dotnet nuget add source --username vestas-power-solutions --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vestas-power-solutions/index.json"

    - name: Restore dependencies
      run: dotnet restore

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'

    - name: Determine version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.9
      with: 
        useConfigFile: true
    
    - name: Build
      run: dotnet build --no-restore -c Release -p:Version=${{ steps.gitversion.outputs.SemVer }}
    
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

    # - name: Tag & push commit
    #   run: |
    #     git tag v${{ steps.gitversion.outputs.SemVer }}
    #     git push origin v${{ steps.gitversion.outputs.SemVer }}

    - name: Package Model
      run: dotnet pack ./HelloWorld --no-build --no-restore -c Release -o publish/nupkg/ -p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}

    - name: Build artifacts
      run: dotnet publish ./HelloWorld -c Release --self-contained --nologo -p:PublishTrimmed=true --output publish/api/ -r win-x64 -p:Version=${{ steps.gitversion.outputs.SemVer }}

    - name: Create nuget package from publish
      uses: cake-build/cake-action@v1
      with:
        script-path: nuget.cake
        target: Create-Nuget
        verbosity: Diagnostic
        arguments: |
          srcPath: "publish/api/*.*"
          nuspecPath: "./HelloWorld/HelloWorld.nuspec"
          libraryVersion: "${{ steps.gitversion.outputs.SemVer }}"
          nugetOutput: "publish/nupkg"

    - name: Pack artifacts
      uses: papeloto/action-zip@v1
      with:
        dest: hello-world-win-x64-v${{ steps.gitversion.outputs.SemVer }}.zip
        files: publish/
    
    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-v${{ steps.gitversion.outputs.SemVer }}
        path: ./*.zip

    # - name: Publish release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: ./*.zip
    #     tag_name: ${{ steps.gitversion.outputs.SemVer }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
